name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Build and test
        run: |
          # ここにビルドとテストのコマンドを記述
          echo "Build and test steps"

      - name: Upload build artifacts
        run: |
          # ここにビルド成果物をS3にアップロードするコマンドを記述
          aws s3 cp build/ s3://my-bucket/build/ --recursive

      - name: Deploy to ECS
        run: |
          # ここにECSへのデプロイコマンドを記述
          aws ecs update-service --cluster my-ecs-cluster --service my-ecs-service --force-new-deployment
